// Generated by CoffeeScript 1.10.0
var moment;

moment = require('moment-timezone');

module.exports.title = function() {
  console.log('# Base');
};

module.exports.cook = function() {
  var hello, name, now;
  name = 'Recipe';
  hello = "Hello " + name + "!";
  console.log(hello);
  now = moment().utc();
  console.log(now.format());
  now = moment().tz('Asia/Tokyo');
  console.log(now.format());
};
