// Generated by CoffeeScript 1.10.0
var LoggerFactory;

LoggerFactory = (function() {
  function LoggerFactory() {}

  LoggerFactory.__log4js = require('log4js');

  LoggerFactory.__log4js.clearAppenders();

  LoggerFactory.__loggers = {};

  LoggerFactory.__appenderConfig = {
    type: 'console',
    layout: {
      type: 'pattern',
      pattern: "%d{ISO8601_WITH_TZ_OFFSET} [#%z] %c: %-5p %m"
    }
  };

  LoggerFactory.getLogger = function(name) {
    var appender, logger;
    if (name in this.__loggers) {
      return this.__loggers[name];
    }
    appender = this.__log4js.appenderMakers['console'](this.__appenderConfig);
    this.__log4js.addAppender(appender, name);
    logger = this.__log4js.getLogger(name);
    this.__loggers[name] = logger;
    return logger;
  };

  return LoggerFactory;

})();

module.exports = {
  LoggerFactory: LoggerFactory
};
