// Generated by CoffeeScript 1.10.0
var cook, recipes;

cook = function(recipes) {
  var i, len, recipe, recipe_mod;
  for (i = 0, len = recipes.length; i < len; i++) {
    recipe = recipes[i];
    recipe_mod = require(recipe);
    console.log('');
    recipe_mod.title();
    recipe_mod.cook();
  }
};

recipes = ['./cookbook/recipe_base', './cookbook/recipe_loop'];

cook(recipes);
