// Generated by CoffeeScript 1.10.0
var cook, logger, logging, path, title;

path = require('path');

logging = require('./util/logging');

logger = logging.LoggerFactory.getLogger(path.basename(__filename));

title = function() {
  logger.debug('# Loop');
};

cook = function() {
  var i, len, num, nums, pow, results;
  nums = [0, 1, 2, 3, 4];
  pow = function(x) {
    return Math.pow(x, 2);
  };
  results = [];
  for (i = 0, len = nums.length; i < len; i++) {
    num = nums[i];
    results.push(pow(num));
  }
  logger.debug(results);
  results = (function() {
    var j, len1, results1;
    results1 = [];
    for (j = 0, len1 = nums.length; j < len1; j++) {
      num = nums[j];
      results1.push(pow(num));
    }
    return results1;
  })();
  logger.debug(results);
  results = nums.map(function(num) {
    return pow(num);
  });
  logger.debug(results);
};

module.exports = {
  title: title,
  cook: cook
};
