// Generated by CoffeeScript 1.10.0
var cook, logger, logging, moment, path, title;

moment = require('moment-timezone');

path = require('path');

logging = require('./util/logging');

logger = logging.LoggerFactory.getLogger(path.basename(__filename));

title = function() {
  logger.debug('# Base');
};

cook = function() {
  var hello, name, now;
  name = 'Recipe';
  hello = "Hello " + name + "!";
  logger.debug(hello);
  now = moment().utc();
  logger.debug(now.format());
  now = moment().tz('Asia/Tokyo');
  logger.debug(now.format());
};

module.exports = {
  title: title,
  cook: cook
};
